### ISSUE TITLE
Multiple IK solutions

### ISSUE THREAD

**Issue by prajwalresearch** [caelan/pybullet-planning#8]
Hello, Thanks for such a great library.
I have a problem where I do not know the current joint config and I am required to get multiple Ik solutions of Franka panda given the current end-effector position and orientation.
I looked up the ikfast.py file and there I found  [pybullet_inverse_Kinematics function](https://github.com/caelan/pybullet-planning/blob/master/pybullet_tools/ikfast/ikfast.py#:~:text=solutions%20%3D%20multiple_sub_inverse_kinematics(robot,first_close%3DTrue%2C%20**kwargs)) .
if I set max-attempts arg greater than 1 would I will be able to get multiple Ik solutions? 
If not can you help  how can I get multiple Ik solutions then for such a problem?
Thanks

**Comment by caelan** [comment]
Yes, and `max_attempts=INF` will return an (infinite) generator of solutions.
