### ISSUE TITLE
question about test_kuka_pick.py

### ISSUE THREAD

**Issue by jlbhb** [caelan/pybullet-planning#9]
I build pybullet and pybullet_plan on my Windows system. but when I run the 'test_kuka_pick.py' ,I got an error in 'utils.py' ,'No module named 'motion_planners'. I want to know how to deal with this error.

**Comment by caelan** [comment]
motion-planners is actually already included as a submodule. All you need to do is run `pybullet-planning$ git pull --recurse-submodules`.
